# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.checkout_quote import CheckoutQuote
from ..types.checkout_session import CheckoutSession
from ..types.lab_test_collection_method import LabTestCollectionMethod
from ..types.order_set_request import OrderSetRequest
from .raw_client import AsyncRawCheckoutClient, RawCheckoutClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class CheckoutClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawCheckoutClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawCheckoutClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawCheckoutClient
        """
        return self._raw_client

    def get_checkout_session(
        self, checkout_session_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> CheckoutSession:
        """
        Get the checkout session snapshot.

        In-flight sessions reflect live workflow state; terminal sessions are
        served from the persisted snapshot. A read arriving moments after session
        creation can 404 until the workflow's first persistence write commits.

        Parameters
        ----------
        checkout_session_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CheckoutSession
            Successful Response

        Examples
        --------
        from junction import Junction

        client = Junction(
            api_key="YOUR_API_KEY",
        )
        client.checkout.get_checkout_session(
            checkout_session_id="checkout_session_id",
        )
        """
        _response = self._raw_client.get_checkout_session(checkout_session_id, request_options=request_options)
        return _response.data

    def confirm_checkout_session(
        self, checkout_session_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> CheckoutSession:
        """
        Confirm the checkout session after completing payment.

        In-flight sessions verify payment against the channel (Stripe) and report
        order progress; terminal sessions return the persisted snapshot untouched.

        Parameters
        ----------
        checkout_session_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CheckoutSession
            Successful Response

        Examples
        --------
        from junction import Junction

        client = Junction(
            api_key="YOUR_API_KEY",
        )
        client.checkout.confirm_checkout_session(
            checkout_session_id="checkout_session_id",
        )
        """
        _response = self._raw_client.confirm_checkout_session(checkout_session_id, request_options=request_options)
        return _response.data

    def create_quote(
        self,
        *,
        order_set: OrderSetRequest,
        modality: LabTestCollectionMethod,
        priority: bool,
        us_state: str,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CheckoutQuote:
        """
        Parameters
        ----------
        order_set : OrderSetRequest

        modality : LabTestCollectionMethod
            ℹ️ This enum is non-exhaustive.

        priority : bool

        us_state : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CheckoutQuote
            Successful Response

        Examples
        --------
        from junction import Junction, LabTestCollectionMethod, OrderSetRequest

        client = Junction(
            api_key="YOUR_API_KEY",
        )
        client.checkout.create_quote(
            order_set=OrderSetRequest(),
            modality=LabTestCollectionMethod.TESTKIT,
            priority=True,
            us_state="us_state",
        )
        """
        _response = self._raw_client.create_quote(
            order_set=order_set,
            modality=modality,
            priority=priority,
            us_state=us_state,
            request_options=request_options,
        )
        return _response.data

    def refine_quote(
        self,
        quote_id: str,
        *,
        priority: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CheckoutQuote:
        """
        Parameters
        ----------
        quote_id : str

        priority : typing.Optional[bool]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CheckoutQuote
            Successful Response

        Examples
        --------
        from junction import Junction

        client = Junction(
            api_key="YOUR_API_KEY",
        )
        client.checkout.refine_quote(
            quote_id="quote_id",
        )
        """
        _response = self._raw_client.refine_quote(quote_id, priority=priority, request_options=request_options)
        return _response.data

    def get_quote(self, quote_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> CheckoutQuote:
        """
        Parameters
        ----------
        quote_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CheckoutQuote
            Successful Response

        Examples
        --------
        from junction import Junction

        client = Junction(
            api_key="YOUR_API_KEY",
        )
        client.checkout.get_quote(
            quote_id="quote_id",
        )
        """
        _response = self._raw_client.get_quote(quote_id, request_options=request_options)
        return _response.data


class AsyncCheckoutClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawCheckoutClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawCheckoutClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawCheckoutClient
        """
        return self._raw_client

    async def get_checkout_session(
        self, checkout_session_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> CheckoutSession:
        """
        Get the checkout session snapshot.

        In-flight sessions reflect live workflow state; terminal sessions are
        served from the persisted snapshot. A read arriving moments after session
        creation can 404 until the workflow's first persistence write commits.

        Parameters
        ----------
        checkout_session_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CheckoutSession
            Successful Response

        Examples
        --------
        import asyncio

        from junction import AsyncJunction

        client = AsyncJunction(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.checkout.get_checkout_session(
                checkout_session_id="checkout_session_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_checkout_session(checkout_session_id, request_options=request_options)
        return _response.data

    async def confirm_checkout_session(
        self, checkout_session_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> CheckoutSession:
        """
        Confirm the checkout session after completing payment.

        In-flight sessions verify payment against the channel (Stripe) and report
        order progress; terminal sessions return the persisted snapshot untouched.

        Parameters
        ----------
        checkout_session_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CheckoutSession
            Successful Response

        Examples
        --------
        import asyncio

        from junction import AsyncJunction

        client = AsyncJunction(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.checkout.confirm_checkout_session(
                checkout_session_id="checkout_session_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.confirm_checkout_session(
            checkout_session_id, request_options=request_options
        )
        return _response.data

    async def create_quote(
        self,
        *,
        order_set: OrderSetRequest,
        modality: LabTestCollectionMethod,
        priority: bool,
        us_state: str,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CheckoutQuote:
        """
        Parameters
        ----------
        order_set : OrderSetRequest

        modality : LabTestCollectionMethod
            ℹ️ This enum is non-exhaustive.

        priority : bool

        us_state : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CheckoutQuote
            Successful Response

        Examples
        --------
        import asyncio

        from junction import AsyncJunction, LabTestCollectionMethod, OrderSetRequest

        client = AsyncJunction(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.checkout.create_quote(
                order_set=OrderSetRequest(),
                modality=LabTestCollectionMethod.TESTKIT,
                priority=True,
                us_state="us_state",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_quote(
            order_set=order_set,
            modality=modality,
            priority=priority,
            us_state=us_state,
            request_options=request_options,
        )
        return _response.data

    async def refine_quote(
        self,
        quote_id: str,
        *,
        priority: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CheckoutQuote:
        """
        Parameters
        ----------
        quote_id : str

        priority : typing.Optional[bool]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CheckoutQuote
            Successful Response

        Examples
        --------
        import asyncio

        from junction import AsyncJunction

        client = AsyncJunction(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.checkout.refine_quote(
                quote_id="quote_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.refine_quote(quote_id, priority=priority, request_options=request_options)
        return _response.data

    async def get_quote(
        self, quote_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> CheckoutQuote:
        """
        Parameters
        ----------
        quote_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CheckoutQuote
            Successful Response

        Examples
        --------
        import asyncio

        from junction import AsyncJunction

        client = AsyncJunction(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.checkout.get_quote(
                quote_id="quote_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_quote(quote_id, request_options=request_options)
        return _response.data
