# This file was auto-generated by Fern from our API Definition.

import enum


class JunctionEnvironment(enum.Enum):
    PRODUCTION = "https://api.us.junction.com"
    PRODUCTION_EU = "https://api.eu.junction.com"
    SANDBOX = "https://api.sandbox.us.junction.com"
    SANDBOX_EU = "https://api.sandbox.eu.junction.com"
