# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .align_expr_carry import AlignExprCarry


class AlignExpr(UniversalBaseModel):
    """
    Post-aggregation alignment clause for a CQ query.

    `carry` runs after group_by+aggregate, implicitly materialising missing
    datetime buckets before filling them. Omitting `.align()` entirely preserves
    honest-null behaviour; the `carry` field is required when `align` is present.
    """

    carry: AlignExprCarry

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
