# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .period import Period


class AlignExprCarry_CarryForward(UniversalBaseModel):
    mode: typing.Literal["carry_forward"] = "carry_forward"
    max_age: typing.Optional[Period] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class AlignExprCarry_CarryBackward(UniversalBaseModel):
    mode: typing.Literal["carry_backward"] = "carry_backward"
    max_age: typing.Optional[Period] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class AlignExprCarry_CarryNearest(UniversalBaseModel):
    mode: typing.Literal["carry_nearest"] = "carry_nearest"
    span: typing.Optional[Period] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


AlignExprCarry = typing_extensions.Annotated[
    typing.Union[AlignExprCarry_CarryForward, AlignExprCarry_CarryBackward, AlignExprCarry_CarryNearest],
    pydantic.Field(discriminator="mode"),
]
