# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .period import Period


class CarryBackwardExpr(UniversalBaseModel):
    """
    Post-aggregation carry operator: carry-backward.

    For each empty bucket, carries the nearest subsequent non-empty bucket's
    aggregate backward in time. `max_age=None` means no cap; when set,
    enforced >= group_by_period at CQ validation time.
    """

    max_age: typing.Optional[Period] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
