# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .period import Period


class CarryNearestExpr(UniversalBaseModel):
    """
    Post-aggregation carry operator: carry from the nearest non-empty bucket.

    For each empty bucket, borrows the nearest non-empty adjacent bucket's
    aggregate — past or future, whichever is closer. On a tie the past value
    is preferred. `span=None` means no cap; when set, enforced >=
    group_by_period at CQ validation time.
    """

    span: typing.Optional[Period] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
