# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .period import Period


class CarryForwardExpr(UniversalBaseModel):
    """
    Post-aggregation carry operator: last-observation-carried-forward.

    For each empty bucket, carries the most recent prior non-empty bucket's
    aggregate forward. `max_age=None` means no cap (carry indefinitely);
    when set, enforced >= group_by_period at CQ validation time.
    """

    max_age: typing.Optional[Period] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
