# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .checkout_appointment_hold_status import CheckoutAppointmentHoldStatus
from .checkout_session_status import CheckoutSessionStatus


class CheckoutSession(UniversalBaseModel):
    """
    A checkout session collects payment for a quote; once it is paid, the
    order is created. The checkout session endpoints return this object, and
    `checkout.session.*` webhooks carry it as `data`.
    """

    checkout_session_id: str
    status: CheckoutSessionStatus = pydantic.Field()
    """
    ℹ️ This enum is non-exhaustive.
    """

    pay_before: dt.datetime
    payment_resource_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    ID of the Stripe Checkout Session (`cs_...`) or PaymentIntent (`pi_...`) collecting payment. `null` until the payment resource is created.
    """

    order_id: typing.Optional[str] = None
    order_transaction_id: typing.Optional[str] = None
    appointment_hold_status: typing.Optional[CheckoutAppointmentHoldStatus] = pydantic.Field(default=None)
    """
    ℹ️ This enum is non-exhaustive.
    """

    appointment_id: typing.Optional[str] = None
    payment_resource_url: typing.Optional[str] = pydantic.Field(default=None)
    """
    Stripe-hosted payment page URL, for the `checkout_session` payment method. Returned only by the create, get and confirm endpoints while `status` is `unpaid`; always `null` in webhooks.
    """

    payment_resource_client_secret: typing.Optional[str] = pydantic.Field(default=None)
    """
    Client secret for confirming the Stripe PaymentIntent with Stripe.js, for the `payment_intent` payment method. Returned only by the create, get and confirm endpoints while `status` is `unpaid`; always `null` in webhooks.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
