# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .checkout_appointment_hold_status import CheckoutAppointmentHoldStatus
from .checkout_session_status import CheckoutSessionStatus


class CheckoutSession(UniversalBaseModel):
    """
    The checkout session snapshot. One schema is shared by the REST
    endpoints and the `checkout.session.*` webhook bodies.

    Invariant on `payment_resource_url` / `payment_resource_client_secret`:
    they are populated only on responses served from live workflow state over
    the authenticated API while the session is unpaid, and are always `None`
    everywhere else. In particular they are never populated in a webhook body
    — the todo row, the logbook and the delivery pipeline all retain what they
    are handed, so payment material must not enter any of them. Two things
    hold that: `from_row` never sets the pair, and
    `PublishCheckoutSessionEventTodoContext` strips it on validation, before
    the event is persisted or recorded. Once the session leaves `unpaid`
    they are `None` on every response, because the material is no longer
    actionable.
    """

    checkout_session_id: str
    status: CheckoutSessionStatus = pydantic.Field()
    """
    ℹ️ This enum is non-exhaustive.
    """

    pay_before: dt.datetime
    payment_resource_id: typing.Optional[str] = None
    order_id: typing.Optional[str] = None
    order_transaction_id: typing.Optional[str] = None
    appointment_hold_status: typing.Optional[CheckoutAppointmentHoldStatus] = pydantic.Field(default=None)
    """
    ℹ️ This enum is non-exhaustive.
    """

    appointment_id: typing.Optional[str] = None
    payment_resource_url: typing.Optional[str] = None
    payment_resource_client_secret: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
