# This file was auto-generated by Fern from our API Definition.

import typing

from ..core import enum

T_Result = typing.TypeVar("T_Result")


class CheckoutAppointmentHoldStatus(enum.StrEnum):
    """
    Public view of the checkout's PSC appointment hold. `None` on the
    snapshot means no appointment was requested. `held` covers both a live
    vendor hold and the attached appointment (`appointment_id` set); `failed`
    covers every way the hold ended without one (slot gone, PSC unreachable,
    released on expiry, cancellation, or operator request). ℹ️ This enum is non-exhaustive.
    """

    PENDING = "pending"
    HELD = "held"
    FAILED = "failed"
    _UNKNOWN = "__CHECKOUTAPPOINTMENTHOLDSTATUS_UNKNOWN__"
    """
    This member is used for forward compatibility. If the value is not recognized by the enum, it will be stored here, and the raw value is accessible through `.value`.
    """

    @classmethod
    def _missing_(cls, value: typing.Any) -> "CheckoutAppointmentHoldStatus":
        unknown = cls._UNKNOWN
        unknown._value_ = value
        return unknown

    def visit(
        self,
        pending: typing.Callable[[], T_Result],
        held: typing.Callable[[], T_Result],
        failed: typing.Callable[[], T_Result],
        _unknown_member: typing.Callable[[str], T_Result],
    ) -> T_Result:
        if self is CheckoutAppointmentHoldStatus.PENDING:
            return pending()
        if self is CheckoutAppointmentHoldStatus.HELD:
            return held()
        if self is CheckoutAppointmentHoldStatus.FAILED:
            return failed()
        return _unknown_member(self._value_)
