# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .checkout_quote_line_item_code import CheckoutQuoteLineItemCode


class CheckoutQuoteLineItem(UniversalBaseModel):
    code: CheckoutQuoteLineItemCode = pydantic.Field()
    """
    ℹ️ This enum is non-exhaustive.
    """

    amount_minor: int
    currency: typing.Literal["USD"] = "USD"

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
