# This file was auto-generated by Fern from our API Definition.

import typing

from ..core import enum

T_Result = typing.TypeVar("T_Result")


class CheckoutQuoteLineItemCode(enum.StrEnum):
    """
    ℹ️ This enum is non-exhaustive.
    """

    LAB_TEST_FEE = "lab_test_fee"
    DRAW_FEE = "draw_fee"
    _UNKNOWN = "__CHECKOUTQUOTELINEITEMCODE_UNKNOWN__"
    """
    This member is used for forward compatibility. If the value is not recognized by the enum, it will be stored here, and the raw value is accessible through `.value`.
    """

    @classmethod
    def _missing_(cls, value: typing.Any) -> "CheckoutQuoteLineItemCode":
        unknown = cls._UNKNOWN
        unknown._value_ = value
        return unknown

    def visit(
        self,
        lab_test_fee: typing.Callable[[], T_Result],
        draw_fee: typing.Callable[[], T_Result],
        _unknown_member: typing.Callable[[str], T_Result],
    ) -> T_Result:
        if self is CheckoutQuoteLineItemCode.LAB_TEST_FEE:
            return lab_test_fee()
        if self is CheckoutQuoteLineItemCode.DRAW_FEE:
            return draw_fee()
        return _unknown_member(self._value_)
