# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .checkout_session_status import CheckoutSessionStatus


class CheckoutSession(UniversalBaseModel):
    checkout_id: str
    status: CheckoutSessionStatus = pydantic.Field()
    """
    ℹ️ This enum is non-exhaustive.
    """

    pay_before: dt.datetime
    payment_resource_id: typing.Optional[str] = None
    order_id: typing.Optional[str] = None
    order_transaction_id: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
