# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .checkout_quote_line_item import CheckoutQuoteLineItem
from .lab_test_collection_method import LabTestCollectionMethod
from .order_set_request import OrderSetRequest
from .walk_in_collection_network_slug import WalkInCollectionNetworkSlug


class CheckoutQuote(UniversalBaseModel):
    id: str
    parent_id: typing.Optional[str] = None
    created_at: dt.datetime
    expires_at: dt.datetime
    modality: LabTestCollectionMethod = pydantic.Field()
    """
    ℹ️ This enum is non-exhaustive.
    """

    priority: bool
    us_state: str
    order_set: OrderSetRequest
    walk_in_collection_networks: typing.List[WalkInCollectionNetworkSlug]
    line_items: typing.List[CheckoutQuoteLineItem]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
