# This file was auto-generated by Fern from our API Definition.

import typing

from ..core import enum

T_Result = typing.TypeVar("T_Result")


class CheckoutSessionPaymentMethod(enum.StrEnum):
    """
    ℹ️ This enum is non-exhaustive.
    """

    CHECKOUT_SESSION = "checkout_session"
    PAYMENT_INTENT = "payment_intent"
    _UNKNOWN = "__CHECKOUTSESSIONPAYMENTMETHOD_UNKNOWN__"
    """
    This member is used for forward compatibility. If the value is not recognized by the enum, it will be stored here, and the raw value is accessible through `.value`.
    """

    @classmethod
    def _missing_(cls, value: typing.Any) -> "CheckoutSessionPaymentMethod":
        unknown = cls._UNKNOWN
        unknown._value_ = value
        return unknown

    def visit(
        self,
        checkout_session: typing.Callable[[], T_Result],
        payment_intent: typing.Callable[[], T_Result],
        _unknown_member: typing.Callable[[str], T_Result],
    ) -> T_Result:
        if self is CheckoutSessionPaymentMethod.CHECKOUT_SESSION:
            return checkout_session()
        if self is CheckoutSessionPaymentMethod.PAYMENT_INTENT:
            return payment_intent()
        return _unknown_member(self._value_)
