# This file was auto-generated by Fern from our API Definition.

import typing

from ..core import enum

T_Result = typing.TypeVar("T_Result")


class CheckoutSessionStatus(enum.StrEnum):
    """
    ℹ️ This enum is non-exhaustive.
    """

    UNPAID = "unpaid"
    PAID = "paid"
    EXPIRED = "expired"
    CANCELLED = "cancelled"
    _UNKNOWN = "__CHECKOUTSESSIONSTATUS_UNKNOWN__"
    """
    This member is used for forward compatibility. If the value is not recognized by the enum, it will be stored here, and the raw value is accessible through `.value`.
    """

    @classmethod
    def _missing_(cls, value: typing.Any) -> "CheckoutSessionStatus":
        unknown = cls._UNKNOWN
        unknown._value_ = value
        return unknown

    def visit(
        self,
        unpaid: typing.Callable[[], T_Result],
        paid: typing.Callable[[], T_Result],
        expired: typing.Callable[[], T_Result],
        cancelled: typing.Callable[[], T_Result],
        _unknown_member: typing.Callable[[str], T_Result],
    ) -> T_Result:
        if self is CheckoutSessionStatus.UNPAID:
            return unpaid()
        if self is CheckoutSessionStatus.PAID:
            return paid()
        if self is CheckoutSessionStatus.EXPIRED:
            return expired()
        if self is CheckoutSessionStatus.CANCELLED:
            return cancelled()
        return _unknown_member(self._value_)
