# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class CheckoutSessionAppointment(UniversalBaseModel):
    """
    A PSC slot held with the collection network while the patient pays; it
    becomes the order's appointment once payment creates the order.
    """

    booking_key: str = pydantic.Field()
    """
    Slot token from the PSC appointment availability endpoint. The slot must start after the session's payment deadline and, when the quote lists collection networks, belong to one of them.
    """

    appointment_notes: str = pydantic.Field()
    """
    Notes stored on the appointment once it is attached to the order.
    """

    async_confirmation_timeout_millisecond: typing.Optional[int] = pydantic.Field(default=None)
    """
    How long the hold keeps retrying with the collection network before it is reported as failed.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
