# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .match_review_webhook_payload import MatchReviewWebhookPayload


class ClientFacingMatchReviewChanged(UniversalBaseModel):
    event_type: typing.Literal["labtest.match_review.created"] = "labtest.match_review.created"
    team_id: str
    data: MatchReviewWebhookPayload

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
