# This file was auto-generated by Fern from our API Definition.

import typing

from ..core import enum

T_Result = typing.TypeVar("T_Result")


class ClientFacingForcedExpiratoryVolume1ChangedEventType(enum.StrEnum):
    DAILY_DATA_FORCED_EXPIRATORY_VOLUME1CREATED = "daily.data.forced_expiratory_volume_1.created"
    DAILY_DATA_FORCED_EXPIRATORY_VOLUME1UPDATED = "daily.data.forced_expiratory_volume_1.updated"
    _UNKNOWN = "__CLIENTFACINGFORCEDEXPIRATORYVOLUME1CHANGEDEVENTTYPE_UNKNOWN__"
    """
    This member is used for forward compatibility. If the value is not recognized by the enum, it will be stored here, and the raw value is accessible through `.value`.
    """

    @classmethod
    def _missing_(cls, value: typing.Any) -> "ClientFacingForcedExpiratoryVolume1ChangedEventType":
        unknown = cls._UNKNOWN
        unknown._value_ = value
        return unknown

    def visit(
        self,
        daily_data_forced_expiratory_volume1created: typing.Callable[[], T_Result],
        daily_data_forced_expiratory_volume1updated: typing.Callable[[], T_Result],
        _unknown_member: typing.Callable[[str], T_Result],
    ) -> T_Result:
        if self is ClientFacingForcedExpiratoryVolume1ChangedEventType.DAILY_DATA_FORCED_EXPIRATORY_VOLUME1CREATED:
            return daily_data_forced_expiratory_volume1created()
        if self is ClientFacingForcedExpiratoryVolume1ChangedEventType.DAILY_DATA_FORCED_EXPIRATORY_VOLUME1UPDATED:
            return daily_data_forced_expiratory_volume1updated()
        return _unknown_member(self._value_)
