# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .checkout_quote import CheckoutQuote


class ClientFacingCheckoutQuoteCreated(UniversalBaseModel):
    event_type: typing.Literal["checkout.quote.created"] = "checkout.quote.created"
    team_id: str
    data: CheckoutQuote

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
