# This file was auto-generated by Fern from our API Definition.

import typing

from ..core import enum

T_Result = typing.TypeVar("T_Result")


class CollectionInferenceSource(enum.StrEnum):
    """
    ℹ️ This enum is non-exhaustive.
    """

    LAB_ARRIVAL = "lab_arrival"
    LAB_ACCESSIONING = "lab_accessioning"
    SCHEDULED_APPOINTMENT = "scheduled_appointment"
    DISPATCH_DATE = "dispatch_date"
    _UNKNOWN = "__COLLECTIONINFERENCESOURCE_UNKNOWN__"
    """
    This member is used for forward compatibility. If the value is not recognized by the enum, it will be stored here, and the raw value is accessible through `.value`.
    """

    @classmethod
    def _missing_(cls, value: typing.Any) -> "CollectionInferenceSource":
        unknown = cls._UNKNOWN
        unknown._value_ = value
        return unknown

    def visit(
        self,
        lab_arrival: typing.Callable[[], T_Result],
        lab_accessioning: typing.Callable[[], T_Result],
        scheduled_appointment: typing.Callable[[], T_Result],
        dispatch_date: typing.Callable[[], T_Result],
        _unknown_member: typing.Callable[[str], T_Result],
    ) -> T_Result:
        if self is CollectionInferenceSource.LAB_ARRIVAL:
            return lab_arrival()
        if self is CollectionInferenceSource.LAB_ACCESSIONING:
            return lab_accessioning()
        if self is CollectionInferenceSource.SCHEDULED_APPOINTMENT:
            return scheduled_appointment()
        if self is CollectionInferenceSource.DISPATCH_DATE:
            return dispatch_date()
        return _unknown_member(self._value_)
