# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .critical_care_pricing_condition import CriticalCarePricingCondition
from .reflex_pricing_condition import ReflexPricingCondition
from .us_state_pricing_condition import UsStatePricingCondition


class ComponentPricingConditions(UniversalBaseModel):
    us_state: typing.Optional[UsStatePricingCondition] = None
    reflex: typing.Optional[ReflexPricingCondition] = None
    critical_care: typing.Optional[CriticalCarePricingCondition] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
