# This file was auto-generated by Fern from our API Definition.

import typing

from ..core import enum

T_Result = typing.TypeVar("T_Result")


class EtaUpdateSource(enum.StrEnum):
    """
    ℹ️ This enum is non-exhaustive.
    """

    LAB = "lab"
    JUNCTION = "junction"
    PATIENT = "patient"
    _UNKNOWN = "__ETAUPDATESOURCE_UNKNOWN__"
    """
    This member is used for forward compatibility. If the value is not recognized by the enum, it will be stored here, and the raw value is accessible through `.value`.
    """

    @classmethod
    def _missing_(cls, value: typing.Any) -> "EtaUpdateSource":
        unknown = cls._UNKNOWN
        unknown._value_ = value
        return unknown

    def visit(
        self,
        lab: typing.Callable[[], T_Result],
        junction: typing.Callable[[], T_Result],
        patient: typing.Callable[[], T_Result],
        _unknown_member: typing.Callable[[str], T_Result],
    ) -> T_Result:
        if self is EtaUpdateSource.LAB:
            return lab()
        if self is EtaUpdateSource.JUNCTION:
            return junction()
        if self is EtaUpdateSource.PATIENT:
            return patient()
        return _unknown_member(self._value_)
