# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .generic_pricing_component_pricing import GenericPricingComponentPricing
from .pricing_component_id import PricingComponentId


class GenericPricingComponent(UniversalBaseModel):
    id: PricingComponentId = pydantic.Field()
    """
    ℹ️ This enum is non-exhaustive.
    """

    pricing: GenericPricingComponentPricing

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
