# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .lab_test_panel_pricing import LabTestPanelPricing


class GetLabTestPricingResponse(UniversalBaseModel):
    """
    Aggregated per-panel pricing, keyed by lab test ID.
    """

    currency: typing.Optional[typing.Literal["USD"]] = None
    data: typing.Dict[str, LabTestPanelPricing]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
