# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .lab_test_collection_method import LabTestCollectionMethod
from .labs import Labs


class LabTestPromotionSource(UniversalBaseModel):
    name: str
    description: str
    method: LabTestCollectionMethod = pydantic.Field()
    """
    ℹ️ This enum is non-exhaustive.
    """

    fasting: bool
    lab_slug: Labs = pydantic.Field()
    """
    ℹ️ This enum is non-exhaustive.
    """

    provider_ids: typing.List[str]
    source_sandbox_lab_test_id: str

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
