# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .lab_charge_pricing_component_marker_breakdown_value import LabChargePricingComponentMarkerBreakdownValue
from .lab_charge_pricing_component_pricing import LabChargePricingComponentPricing


class LabChargePricingComponent(UniversalBaseModel):
    id: typing.Literal["lab_charge"] = "lab_charge"
    pricing: LabChargePricingComponentPricing
    marker_breakdown: typing.Optional[
        typing.Dict[str, typing.Optional[LabChargePricingComponentMarkerBreakdownValue]]
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
