# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .lab_test_panel_pricing_marker_breakdown_value import LabTestPanelPricingMarkerBreakdownValue
from .lab_test_panel_pricing_pricing import LabTestPanelPricingPricing


class LabTestPanelPricing(UniversalBaseModel):
    pricing: LabTestPanelPricingPricing
    marker_breakdown: typing.Optional[typing.Dict[str, typing.Optional[LabTestPanelPricingMarkerBreakdownValue]]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
