# This file was auto-generated by Fern from our API Definition.

import typing

from .specified_pricing_marker_pricing_conditions import SpecifiedPricingMarkerPricingConditions
from .unspecified_pricing import UnspecifiedPricing

LabTestPanelPricingPricing = typing.Union[SpecifiedPricingMarkerPricingConditions, UnspecifiedPricing]
