# This file was auto-generated by Fern from our API Definition.

import typing

from ..core import enum

T_Result = typing.TypeVar("T_Result")


class MatchCandidateConfidenceLevel(enum.StrEnum):
    """
    ℹ️ This enum is non-exhaustive.
    """

    HIGH = "high"
    MEDIUM = "medium"
    LOW = "low"
    _UNKNOWN = "__MATCHCANDIDATECONFIDENCELEVEL_UNKNOWN__"
    """
    This member is used for forward compatibility. If the value is not recognized by the enum, it will be stored here, and the raw value is accessible through `.value`.
    """

    @classmethod
    def _missing_(cls, value: typing.Any) -> "MatchCandidateConfidenceLevel":
        unknown = cls._UNKNOWN
        unknown._value_ = value
        return unknown

    def visit(
        self,
        high: typing.Callable[[], T_Result],
        medium: typing.Callable[[], T_Result],
        low: typing.Callable[[], T_Result],
        _unknown_member: typing.Callable[[str], T_Result],
    ) -> T_Result:
        if self is MatchCandidateConfidenceLevel.HIGH:
            return high()
        if self is MatchCandidateConfidenceLevel.MEDIUM:
            return medium()
        if self is MatchCandidateConfidenceLevel.LOW:
            return low()
        return _unknown_member(self._value_)
