# This file was auto-generated by Fern from our API Definition.

import typing

from ..core import enum

T_Result = typing.TypeVar("T_Result")


class MatchReviewResolutionAction(enum.StrEnum):
    """
    ℹ️ This enum is non-exhaustive.
    """

    ACCEPT = "accept"
    REJECT = "reject"
    UNSURE = "unsure"
    _UNKNOWN = "__MATCHREVIEWRESOLUTIONACTION_UNKNOWN__"
    """
    This member is used for forward compatibility. If the value is not recognized by the enum, it will be stored here, and the raw value is accessible through `.value`.
    """

    @classmethod
    def _missing_(cls, value: typing.Any) -> "MatchReviewResolutionAction":
        unknown = cls._UNKNOWN
        unknown._value_ = value
        return unknown

    def visit(
        self,
        accept: typing.Callable[[], T_Result],
        reject: typing.Callable[[], T_Result],
        unsure: typing.Callable[[], T_Result],
        _unknown_member: typing.Callable[[str], T_Result],
    ) -> T_Result:
        if self is MatchReviewResolutionAction.ACCEPT:
            return accept()
        if self is MatchReviewResolutionAction.REJECT:
            return reject()
        if self is MatchReviewResolutionAction.UNSURE:
            return unsure()
        return _unknown_member(self._value_)
