# This file was auto-generated by Fern from our API Definition.

import typing

from ..core import enum

T_Result = typing.TypeVar("T_Result")


class MatchReviewTransitionStatus(enum.StrEnum):
    """
    Status a raw_result_match_updates row can transition to.

    Unlike `MatchReviewStatus` this single status tells you the exact decision
    at each point without looking through other columns (accepted/rejected are
    baked in here) ℹ️ This enum is non-exhaustive.
    """

    MATCHED = "matched"
    PENDING_CUSTOMER_REVIEW = "pending_customer_review"
    PENDING_CUSTOMER_REVIEW_IN_PROGRESS = "pending_customer_review:in_progress"
    PENDING_OPS_REVIEW = "pending_ops_review"
    RESOLVED_ACCEPTED = "resolved:accepted"
    RESOLVED_REJECTED = "resolved:rejected"
    _UNKNOWN = "__MATCHREVIEWTRANSITIONSTATUS_UNKNOWN__"
    """
    This member is used for forward compatibility. If the value is not recognized by the enum, it will be stored here, and the raw value is accessible through `.value`.
    """

    @classmethod
    def _missing_(cls, value: typing.Any) -> "MatchReviewTransitionStatus":
        unknown = cls._UNKNOWN
        unknown._value_ = value
        return unknown

    def visit(
        self,
        matched: typing.Callable[[], T_Result],
        pending_customer_review: typing.Callable[[], T_Result],
        pending_customer_review_in_progress: typing.Callable[[], T_Result],
        pending_ops_review: typing.Callable[[], T_Result],
        resolved_accepted: typing.Callable[[], T_Result],
        resolved_rejected: typing.Callable[[], T_Result],
        _unknown_member: typing.Callable[[str], T_Result],
    ) -> T_Result:
        if self is MatchReviewTransitionStatus.MATCHED:
            return matched()
        if self is MatchReviewTransitionStatus.PENDING_CUSTOMER_REVIEW:
            return pending_customer_review()
        if self is MatchReviewTransitionStatus.PENDING_CUSTOMER_REVIEW_IN_PROGRESS:
            return pending_customer_review_in_progress()
        if self is MatchReviewTransitionStatus.PENDING_OPS_REVIEW:
            return pending_ops_review()
        if self is MatchReviewTransitionStatus.RESOLVED_ACCEPTED:
            return resolved_accepted()
        if self is MatchReviewTransitionStatus.RESOLVED_REJECTED:
            return resolved_rejected()
        return _unknown_member(self._value_)
