# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .match_decision_code import MatchDecisionCode
from .match_review_resolution_action import MatchReviewResolutionAction
from .match_review_status import MatchReviewStatus
from .match_sub_reason_code import MatchSubReasonCode


class MatchReviewWebhookPayload(UniversalBaseModel):
    id: str
    status: MatchReviewStatus = pydantic.Field()
    """
    ℹ️ This enum is non-exhaustive.
    """

    decision_code: MatchDecisionCode = pydantic.Field()
    """
    ℹ️ This enum is non-exhaustive.
    """

    sub_reason_codes: typing.Optional[typing.List[MatchSubReasonCode]] = None
    resolution_action: typing.Optional[MatchReviewResolutionAction] = pydantic.Field(default=None)
    """
    ℹ️ This enum is non-exhaustive.
    """

    resolved_user_id: typing.Optional[str] = None
    resolved_order_id: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
