# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .match_candidate_confidence_level import MatchCandidateConfidenceLevel
from .match_candidate_reason_code import MatchCandidateReasonCode
from .match_candidate_type import MatchCandidateType
from .order_low_level_status import OrderLowLevelStatus


class MatchReviewCandidate(UniversalBaseModel):
    candidate_type: MatchCandidateType = pydantic.Field()
    """
    ℹ️ This enum is non-exhaustive.
    """

    order_id: typing.Optional[str] = None
    order_transaction_id: typing.Optional[str] = None
    last_status: typing.Optional[OrderLowLevelStatus] = pydantic.Field(default=None)
    """
    ℹ️ This enum is non-exhaustive.
    """

    confidence_level: MatchCandidateConfidenceLevel = pydantic.Field()
    """
    ℹ️ This enum is non-exhaustive.
    """

    confidence_score: typing.Optional[float] = None
    reasons: typing.Optional[typing.List[MatchCandidateReasonCode]] = None
    marker_overlap: typing.Optional[typing.Dict[str, typing.Any]] = None
    status_context: typing.Optional[typing.Dict[str, typing.Any]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
