# This file was auto-generated by Fern from our API Definition.

import typing

from ..core import enum

T_Result = typing.TypeVar("T_Result")


class MatchCandidateReasonCode(enum.StrEnum):
    """
    ℹ️ This enum is non-exhaustive.
    """

    SAMPLE_ID_MATCH = "sample_id_match"
    LAB_ACCOUNT_MISMATCH = "lab_account_mismatch"
    MATCHED_COMPLETED_ORDER = "matched_completed_order"
    MATCHED_CANCELLED_ORDER = "matched_cancelled_order"
    INVALID_COLLECTION_STATE = "invalid_collection_state"
    DEMOGRAPHIC_MISMATCH = "demographic_mismatch"
    DEMOGRAPHIC_MATCH = "demographic_match"
    POSSIBLE_WRONG_LAB = "possible_wrong_lab"
    SAME_LAB = "same_lab"
    SAME_USER = "same_user"
    MARKER_OVERLAP_EXACT = "marker_overlap_exact"
    MARKER_OVERLAP_PARTIAL = "marker_overlap_partial"
    MARKER_OVERLAP_NONE = "marker_overlap_none"
    _UNKNOWN = "__MATCHCANDIDATEREASONCODE_UNKNOWN__"
    """
    This member is used for forward compatibility. If the value is not recognized by the enum, it will be stored here, and the raw value is accessible through `.value`.
    """

    @classmethod
    def _missing_(cls, value: typing.Any) -> "MatchCandidateReasonCode":
        unknown = cls._UNKNOWN
        unknown._value_ = value
        return unknown

    def visit(
        self,
        sample_id_match: typing.Callable[[], T_Result],
        lab_account_mismatch: typing.Callable[[], T_Result],
        matched_completed_order: typing.Callable[[], T_Result],
        matched_cancelled_order: typing.Callable[[], T_Result],
        invalid_collection_state: typing.Callable[[], T_Result],
        demographic_mismatch: typing.Callable[[], T_Result],
        demographic_match: typing.Callable[[], T_Result],
        possible_wrong_lab: typing.Callable[[], T_Result],
        same_lab: typing.Callable[[], T_Result],
        same_user: typing.Callable[[], T_Result],
        marker_overlap_exact: typing.Callable[[], T_Result],
        marker_overlap_partial: typing.Callable[[], T_Result],
        marker_overlap_none: typing.Callable[[], T_Result],
        _unknown_member: typing.Callable[[str], T_Result],
    ) -> T_Result:
        if self is MatchCandidateReasonCode.SAMPLE_ID_MATCH:
            return sample_id_match()
        if self is MatchCandidateReasonCode.LAB_ACCOUNT_MISMATCH:
            return lab_account_mismatch()
        if self is MatchCandidateReasonCode.MATCHED_COMPLETED_ORDER:
            return matched_completed_order()
        if self is MatchCandidateReasonCode.MATCHED_CANCELLED_ORDER:
            return matched_cancelled_order()
        if self is MatchCandidateReasonCode.INVALID_COLLECTION_STATE:
            return invalid_collection_state()
        if self is MatchCandidateReasonCode.DEMOGRAPHIC_MISMATCH:
            return demographic_mismatch()
        if self is MatchCandidateReasonCode.DEMOGRAPHIC_MATCH:
            return demographic_match()
        if self is MatchCandidateReasonCode.POSSIBLE_WRONG_LAB:
            return possible_wrong_lab()
        if self is MatchCandidateReasonCode.SAME_LAB:
            return same_lab()
        if self is MatchCandidateReasonCode.SAME_USER:
            return same_user()
        if self is MatchCandidateReasonCode.MARKER_OVERLAP_EXACT:
            return marker_overlap_exact()
        if self is MatchCandidateReasonCode.MARKER_OVERLAP_PARTIAL:
            return marker_overlap_partial()
        if self is MatchCandidateReasonCode.MARKER_OVERLAP_NONE:
            return marker_overlap_none()
        return _unknown_member(self._value_)
