# This file was auto-generated by Fern from our API Definition.

import typing

from ..core import enum

T_Result = typing.TypeVar("T_Result")


class MatchDecisionCode(enum.StrEnum):
    """
    ℹ️ This enum is non-exhaustive.
    """

    MATCH_SAMPLE_ID = "match_sample_id"
    MATCH_COMPLETED = "match_completed"
    MATCH_CANCELLED = "match_cancelled"
    WRONG_COLLECTION = "wrong_collection"
    WRONG_LAB = "wrong_lab"
    MULTIPLE_DEMO_MATCH = "multiple_demo_match"
    MATCH_SAMPLE_ID_MISMATCH_DEMO = "match_sample_id_mismatch_demo"
    MATCH_DEMO = "match_demo"
    NO_MATCH = "no_match"
    _UNKNOWN = "__MATCHDECISIONCODE_UNKNOWN__"
    """
    This member is used for forward compatibility. If the value is not recognized by the enum, it will be stored here, and the raw value is accessible through `.value`.
    """

    @classmethod
    def _missing_(cls, value: typing.Any) -> "MatchDecisionCode":
        unknown = cls._UNKNOWN
        unknown._value_ = value
        return unknown

    def visit(
        self,
        match_sample_id: typing.Callable[[], T_Result],
        match_completed: typing.Callable[[], T_Result],
        match_cancelled: typing.Callable[[], T_Result],
        wrong_collection: typing.Callable[[], T_Result],
        wrong_lab: typing.Callable[[], T_Result],
        multiple_demo_match: typing.Callable[[], T_Result],
        match_sample_id_mismatch_demo: typing.Callable[[], T_Result],
        match_demo: typing.Callable[[], T_Result],
        no_match: typing.Callable[[], T_Result],
        _unknown_member: typing.Callable[[str], T_Result],
    ) -> T_Result:
        if self is MatchDecisionCode.MATCH_SAMPLE_ID:
            return match_sample_id()
        if self is MatchDecisionCode.MATCH_COMPLETED:
            return match_completed()
        if self is MatchDecisionCode.MATCH_CANCELLED:
            return match_cancelled()
        if self is MatchDecisionCode.WRONG_COLLECTION:
            return wrong_collection()
        if self is MatchDecisionCode.WRONG_LAB:
            return wrong_lab()
        if self is MatchDecisionCode.MULTIPLE_DEMO_MATCH:
            return multiple_demo_match()
        if self is MatchDecisionCode.MATCH_SAMPLE_ID_MISMATCH_DEMO:
            return match_sample_id_mismatch_demo()
        if self is MatchDecisionCode.MATCH_DEMO:
            return match_demo()
        if self is MatchDecisionCode.NO_MATCH:
            return no_match()
        return _unknown_member(self._value_)
