# This file was auto-generated by Fern from our API Definition.

import typing

from ..core import enum

T_Result = typing.TypeVar("T_Result")


class MatchCandidateType(enum.StrEnum):
    """
    ℹ️ This enum is non-exhaustive.
    """

    PROVENANCE_ORDER = "provenance_order"
    ORDER_OPTION = "order_option"
    _UNKNOWN = "__MATCHCANDIDATETYPE_UNKNOWN__"
    """
    This member is used for forward compatibility. If the value is not recognized by the enum, it will be stored here, and the raw value is accessible through `.value`.
    """

    @classmethod
    def _missing_(cls, value: typing.Any) -> "MatchCandidateType":
        unknown = cls._UNKNOWN
        unknown._value_ = value
        return unknown

    def visit(
        self,
        provenance_order: typing.Callable[[], T_Result],
        order_option: typing.Callable[[], T_Result],
        _unknown_member: typing.Callable[[str], T_Result],
    ) -> T_Result:
        if self is MatchCandidateType.PROVENANCE_ORDER:
            return provenance_order()
        if self is MatchCandidateType.ORDER_OPTION:
            return order_option()
        return _unknown_member(self._value_)
