# This file was auto-generated by Fern from our API Definition.

import typing

from ..core import enum

T_Result = typing.TypeVar("T_Result")


class MatchReviewStatus(enum.StrEnum):
    """
    ℹ️ This enum is non-exhaustive.
    """

    MATCHED = "matched"
    PENDING_CUSTOMER_REVIEW = "pending_customer_review"
    PENDING_OPS_REVIEW = "pending_ops_review"
    PENDING_CUSTOMER_REVIEW_IN_PROGRESS = "pending_customer_review:in_progress"
    RESOLVED = "resolved"
    _UNKNOWN = "__MATCHREVIEWSTATUS_UNKNOWN__"
    """
    This member is used for forward compatibility. If the value is not recognized by the enum, it will be stored here, and the raw value is accessible through `.value`.
    """

    @classmethod
    def _missing_(cls, value: typing.Any) -> "MatchReviewStatus":
        unknown = cls._UNKNOWN
        unknown._value_ = value
        return unknown

    def visit(
        self,
        matched: typing.Callable[[], T_Result],
        pending_customer_review: typing.Callable[[], T_Result],
        pending_ops_review: typing.Callable[[], T_Result],
        pending_customer_review_in_progress: typing.Callable[[], T_Result],
        resolved: typing.Callable[[], T_Result],
        _unknown_member: typing.Callable[[str], T_Result],
    ) -> T_Result:
        if self is MatchReviewStatus.MATCHED:
            return matched()
        if self is MatchReviewStatus.PENDING_CUSTOMER_REVIEW:
            return pending_customer_review()
        if self is MatchReviewStatus.PENDING_OPS_REVIEW:
            return pending_ops_review()
        if self is MatchReviewStatus.PENDING_CUSTOMER_REVIEW_IN_PROGRESS:
            return pending_customer_review_in_progress()
        if self is MatchReviewStatus.RESOLVED:
            return resolved()
        return _unknown_member(self._value_)
