# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .eta_update_source import EtaUpdateSource
from .order_tracking_impacted_marker import OrderTrackingImpactedMarker


class OrderTrackingUpdate(UniversalBaseModel):
    created_at: dt.datetime
    reason: typing.Optional[str] = None
    revised_estimate: typing.Optional[dt.datetime] = None
    impacted_markers: typing.List[OrderTrackingImpactedMarker]
    source: EtaUpdateSource = pydantic.Field()
    """
    ℹ️ This enum is non-exhaustive.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
