# This file was auto-generated by Fern from our API Definition.

import typing

from .specified_pricing_component_pricing_conditions import SpecifiedPricingComponentPricingConditions
from .unspecified_pricing import UnspecifiedPricing

OrderSetPricingAggregatePricing = typing.Union[SpecifiedPricingComponentPricingConditions, UnspecifiedPricing]
