# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .order_set_fasting_requirement import OrderSetFastingRequirement


class OrderSetParameters(UniversalBaseModel):
    fasting: typing.Optional[OrderSetFastingRequirement] = pydantic.Field(default=None)
    """
    ℹ️ This enum is non-exhaustive.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
