# This file was auto-generated by Fern from our API Definition.

import typing

from ..core import enum

T_Result = typing.TypeVar("T_Result")


class OrderSetFastingRequirement(enum.StrEnum):
    """
    ℹ️ This enum is non-exhaustive.
    """

    FASTING_NOT_REQUIRED = "fasting_not_required"
    FASTING_REQUIRED = "fasting_required"
    _UNKNOWN = "__ORDERSETFASTINGREQUIREMENT_UNKNOWN__"
    """
    This member is used for forward compatibility. If the value is not recognized by the enum, it will be stored here, and the raw value is accessible through `.value`.
    """

    @classmethod
    def _missing_(cls, value: typing.Any) -> "OrderSetFastingRequirement":
        unknown = cls._UNKNOWN
        unknown._value_ = value
        return unknown

    def visit(
        self,
        fasting_not_required: typing.Callable[[], T_Result],
        fasting_required: typing.Callable[[], T_Result],
        _unknown_member: typing.Callable[[str], T_Result],
    ) -> T_Result:
        if self is OrderSetFastingRequirement.FASTING_NOT_REQUIRED:
            return fasting_not_required()
        if self is OrderSetFastingRequirement.FASTING_REQUIRED:
            return fasting_required()
        return _unknown_member(self._value_)
