# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .order_tracking_collection import OrderTrackingCollection
from .order_tracking_expected_at import OrderTrackingExpectedAt
from .order_tracking_marker import OrderTrackingMarker
from .order_tracking_update import OrderTrackingUpdate


class OrderTracking(UniversalBaseModel):
    order_id: str
    expected_at: OrderTrackingExpectedAt
    collected_at: typing.Optional[OrderTrackingCollection] = None
    markers: typing.List[OrderTrackingMarker]
    updates: typing.List[OrderTrackingUpdate]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
