# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .order_tracking_estimate import OrderTrackingEstimate


class OrderTrackingImpactedMarker(UniversalBaseModel):
    id: int
    name: str
    provider_id: typing.Optional[str] = None
    estimates: OrderTrackingEstimate

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
