# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .order_marker_tracking_status import OrderMarkerTrackingStatus
from .order_tracking_estimate import OrderTrackingEstimate
from .order_tracking_result_marker import OrderTrackingResultMarker


class OrderTrackingMarker(UniversalBaseModel):
    id: int
    name: str
    slug: str
    provider_id: typing.Optional[str] = None
    status: OrderMarkerTrackingStatus = pydantic.Field()
    """
    ℹ️ This enum is non-exhaustive.
    """

    expected_at: OrderTrackingEstimate
    results: typing.List[OrderTrackingResultMarker]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
