# This file was auto-generated by Fern from our API Definition.

import typing

from .generic_pricing_component import GenericPricingComponent
from .lab_charge_pricing_component import LabChargePricingComponent

OrderSetPricingComponentsItem = typing.Union[LabChargePricingComponent, GenericPricingComponent]
