# This file was auto-generated by Fern from our API Definition.

import typing

from ..core import enum

T_Result = typing.TypeVar("T_Result")


class OrderMarkerTrackingStatus(enum.StrEnum):
    """
    ℹ️ This enum is non-exhaustive.
    """

    PENDING = "pending"
    INCOMPLETE = "incomplete"
    RESULTED = "resulted"
    _UNKNOWN = "__ORDERMARKERTRACKINGSTATUS_UNKNOWN__"
    """
    This member is used for forward compatibility. If the value is not recognized by the enum, it will be stored here, and the raw value is accessible through `.value`.
    """

    @classmethod
    def _missing_(cls, value: typing.Any) -> "OrderMarkerTrackingStatus":
        unknown = cls._UNKNOWN
        unknown._value_ = value
        return unknown

    def visit(
        self,
        pending: typing.Callable[[], T_Result],
        incomplete: typing.Callable[[], T_Result],
        resulted: typing.Callable[[], T_Result],
        _unknown_member: typing.Callable[[str], T_Result],
    ) -> T_Result:
        if self is OrderMarkerTrackingStatus.PENDING:
            return pending()
        if self is OrderMarkerTrackingStatus.INCOMPLETE:
            return incomplete()
        if self is OrderMarkerTrackingStatus.RESULTED:
            return resulted()
        return _unknown_member(self._value_)
