# This file was auto-generated by Fern from our API Definition.

import typing

from .pricing_modifier_range import PricingModifierRange

PricingModifierMarkerPricingConditionsDeltaAmountMinor = typing.Union[int, PricingModifierRange]
