# This file was auto-generated by Fern from our API Definition.

import typing

from ..core import enum

T_Result = typing.TypeVar("T_Result")


class PricingComponentId(enum.StrEnum):
    """
    ℹ️ This enum is non-exhaustive.
    """

    PLACED_ORDER_CHARGE = "placed_order_charge"
    REQUISITION_CHARGE = "requisition_charge"
    DRAW_CHARGE = "draw_charge"
    MOBILE_PHLEBOTOMY_CHARGE = "mobile_phlebotomy_charge"
    DELIVERED_KIT_CHARGE = "delivered_kit_charge"
    COMPLETED_KIT_CHARGE = "completed_kit_charge"
    CRITICAL_CARE_CHARGE = "critical_care_charge"
    LAB_CHARGE = "lab_charge"
    LAB_PRIORITY_CHARGE = "lab_priority_charge"
    _UNKNOWN = "__PRICINGCOMPONENTID_UNKNOWN__"
    """
    This member is used for forward compatibility. If the value is not recognized by the enum, it will be stored here, and the raw value is accessible through `.value`.
    """

    @classmethod
    def _missing_(cls, value: typing.Any) -> "PricingComponentId":
        unknown = cls._UNKNOWN
        unknown._value_ = value
        return unknown

    def visit(
        self,
        placed_order_charge: typing.Callable[[], T_Result],
        requisition_charge: typing.Callable[[], T_Result],
        draw_charge: typing.Callable[[], T_Result],
        mobile_phlebotomy_charge: typing.Callable[[], T_Result],
        delivered_kit_charge: typing.Callable[[], T_Result],
        completed_kit_charge: typing.Callable[[], T_Result],
        critical_care_charge: typing.Callable[[], T_Result],
        lab_charge: typing.Callable[[], T_Result],
        lab_priority_charge: typing.Callable[[], T_Result],
        _unknown_member: typing.Callable[[str], T_Result],
    ) -> T_Result:
        if self is PricingComponentId.PLACED_ORDER_CHARGE:
            return placed_order_charge()
        if self is PricingComponentId.REQUISITION_CHARGE:
            return requisition_charge()
        if self is PricingComponentId.DRAW_CHARGE:
            return draw_charge()
        if self is PricingComponentId.MOBILE_PHLEBOTOMY_CHARGE:
            return mobile_phlebotomy_charge()
        if self is PricingComponentId.DELIVERED_KIT_CHARGE:
            return delivered_kit_charge()
        if self is PricingComponentId.COMPLETED_KIT_CHARGE:
            return completed_kit_charge()
        if self is PricingComponentId.CRITICAL_CARE_CHARGE:
            return critical_care_charge()
        if self is PricingComponentId.LAB_CHARGE:
            return lab_charge()
        if self is PricingComponentId.LAB_PRIORITY_CHARGE:
            return lab_priority_charge()
        return _unknown_member(self._value_)
