# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .component_pricing_conditions import ComponentPricingConditions
from .pricing_modifier_component_pricing_conditions_delta_amount_minor import (
    PricingModifierComponentPricingConditionsDeltaAmountMinor,
)


class PricingModifierComponentPricingConditions(UniversalBaseModel):
    delta_amount_minor: PricingModifierComponentPricingConditionsDeltaAmountMinor = pydantic.Field()
    """
    Amount delta in the smallest denomination of the currency, e.g. cents for USD.
    """

    conditions: ComponentPricingConditions
    keys: typing.List[str] = pydantic.Field()
    """
    Property names present in conditions, including names unknown to a deserializer.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
