# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .marker_pricing_conditions import MarkerPricingConditions
from .pricing_modifier_marker_pricing_conditions_delta_amount_minor import (
    PricingModifierMarkerPricingConditionsDeltaAmountMinor,
)


class PricingModifierMarkerPricingConditions(UniversalBaseModel):
    delta_amount_minor: PricingModifierMarkerPricingConditionsDeltaAmountMinor = pydantic.Field()
    """
    Amount delta in the smallest denomination of the currency, e.g. cents for USD.
    """

    conditions: MarkerPricingConditions

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
