# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .reliability_column_expr_reliability import ReliabilityColumnExprReliability


class ReliabilityColumnExpr(UniversalBaseModel):
    reliability: ReliabilityColumnExprReliability = pydantic.Field()
    """
    ℹ️ This enum is non-exhaustive.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
