# This file was auto-generated by Fern from our API Definition.

import typing

from ..core import enum

T_Result = typing.TypeVar("T_Result")


class ReliabilityColumnExprReliability(enum.StrEnum):
    """
    ℹ️ This enum is non-exhaustive.
    """

    SOURCE_PROVIDER = "source_provider"
    SOURCE_TYPE = "source_type"
    RESOURCE = "resource"
    WINDOW_START_DATE = "window_start_date"
    WINDOW_END_DATE = "window_end_date"
    WINDOW_DURATION_DAY = "window_duration_day"
    PRESENCE_DAY_COUNT = "presence_day_count"
    PRESENCE_COVERAGE = "presence_coverage"
    PRESENCE_GAP_COUNT = "presence_gap_count"
    PRESENCE_GAP_MAXIMUM_DAY = "presence_gap_maximum_day"
    PRESENCE_RECENCY_DAY = "presence_recency_day"
    PRESENCE_GAP_MEAN_DAY = "presence_gap_mean_day"
    PRESENCE_GAP_STANDARD_DEVIATION_DAY = "presence_gap_standard_deviation_day"
    RELIABILITY_STATUS = "reliability_status"
    CONNECTION_STATUS = "connection_status"
    _UNKNOWN = "__RELIABILITYCOLUMNEXPRRELIABILITY_UNKNOWN__"
    """
    This member is used for forward compatibility. If the value is not recognized by the enum, it will be stored here, and the raw value is accessible through `.value`.
    """

    @classmethod
    def _missing_(cls, value: typing.Any) -> "ReliabilityColumnExprReliability":
        unknown = cls._UNKNOWN
        unknown._value_ = value
        return unknown

    def visit(
        self,
        source_provider: typing.Callable[[], T_Result],
        source_type: typing.Callable[[], T_Result],
        resource: typing.Callable[[], T_Result],
        window_start_date: typing.Callable[[], T_Result],
        window_end_date: typing.Callable[[], T_Result],
        window_duration_day: typing.Callable[[], T_Result],
        presence_day_count: typing.Callable[[], T_Result],
        presence_coverage: typing.Callable[[], T_Result],
        presence_gap_count: typing.Callable[[], T_Result],
        presence_gap_maximum_day: typing.Callable[[], T_Result],
        presence_recency_day: typing.Callable[[], T_Result],
        presence_gap_mean_day: typing.Callable[[], T_Result],
        presence_gap_standard_deviation_day: typing.Callable[[], T_Result],
        reliability_status: typing.Callable[[], T_Result],
        connection_status: typing.Callable[[], T_Result],
        _unknown_member: typing.Callable[[str], T_Result],
    ) -> T_Result:
        if self is ReliabilityColumnExprReliability.SOURCE_PROVIDER:
            return source_provider()
        if self is ReliabilityColumnExprReliability.SOURCE_TYPE:
            return source_type()
        if self is ReliabilityColumnExprReliability.RESOURCE:
            return resource()
        if self is ReliabilityColumnExprReliability.WINDOW_START_DATE:
            return window_start_date()
        if self is ReliabilityColumnExprReliability.WINDOW_END_DATE:
            return window_end_date()
        if self is ReliabilityColumnExprReliability.WINDOW_DURATION_DAY:
            return window_duration_day()
        if self is ReliabilityColumnExprReliability.PRESENCE_DAY_COUNT:
            return presence_day_count()
        if self is ReliabilityColumnExprReliability.PRESENCE_COVERAGE:
            return presence_coverage()
        if self is ReliabilityColumnExprReliability.PRESENCE_GAP_COUNT:
            return presence_gap_count()
        if self is ReliabilityColumnExprReliability.PRESENCE_GAP_MAXIMUM_DAY:
            return presence_gap_maximum_day()
        if self is ReliabilityColumnExprReliability.PRESENCE_RECENCY_DAY:
            return presence_recency_day()
        if self is ReliabilityColumnExprReliability.PRESENCE_GAP_MEAN_DAY:
            return presence_gap_mean_day()
        if self is ReliabilityColumnExprReliability.PRESENCE_GAP_STANDARD_DEVIATION_DAY:
            return presence_gap_standard_deviation_day()
        if self is ReliabilityColumnExprReliability.RELIABILITY_STATUS:
            return reliability_status()
        if self is ReliabilityColumnExprReliability.CONNECTION_STATUS:
            return connection_status()
        return _unknown_member(self._value_)
