# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .pricing_modifier_component_pricing_conditions import PricingModifierComponentPricingConditions


class SpecifiedPricingComponentPricingConditions(UniversalBaseModel):
    base_amount_minor: int = pydantic.Field()
    """
    Amount chargeable in the smallest denomination of the currency, e.g. cents for USD.
    """

    modifiers: typing.Optional[typing.List[PricingModifierComponentPricingConditions]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
