# This file was auto-generated by Fern from our API Definition.

import typing

from ..core import enum

T_Result = typing.TypeVar("T_Result")


class UnspecifiedPricingUnspecified(enum.StrEnum):
    """
    ℹ️ This enum is non-exhaustive.
    """

    REFER_TO_CONTRACT = "refer_to_contract"
    PRICE_UNAVAILABLE = "price_unavailable"
    _UNKNOWN = "__UNSPECIFIEDPRICINGUNSPECIFIED_UNKNOWN__"
    """
    This member is used for forward compatibility. If the value is not recognized by the enum, it will be stored here, and the raw value is accessible through `.value`.
    """

    @classmethod
    def _missing_(cls, value: typing.Any) -> "UnspecifiedPricingUnspecified":
        unknown = cls._UNKNOWN
        unknown._value_ = value
        return unknown

    def visit(
        self,
        refer_to_contract: typing.Callable[[], T_Result],
        price_unavailable: typing.Callable[[], T_Result],
        _unknown_member: typing.Callable[[str], T_Result],
    ) -> T_Result:
        if self is UnspecifiedPricingUnspecified.REFER_TO_CONTRACT:
            return refer_to_contract()
        if self is UnspecifiedPricingUnspecified.PRICE_UNAVAILABLE:
            return price_unavailable()
        return _unknown_member(self._value_)
